typedef unsigned char uint8;
typedef unsigned short uint16;
typedef unsigned int uint32;
typedef unsigned long uint64;
uint8 ShowTPS = 1;
uint8 Ingame = 0;
uint8 DebugMode = 1;
uint8 Pause = 1;
float GameSpeed = 10;